//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EmailItem
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

	public virtual string Label
	{
		get;
		set;
	}

	public virtual PersonItem Person
	{
		get;
		set;
	}

}

