//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PersonItem
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string FirstName
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string Gender
	{
		get;
		set;
	}

	public virtual string BirthDate
	{
		get;
		set;
	}

}

